CREATE TABLE IF NOT EXISTS RoomDurableObject (id TEXT PRIMARY KEY);
CREATE TABLE IF NOT EXISTS SyncDurableObject (id TEXT PRIMARY KEY);
CREATE TABLE IF NOT EXISTS FederationDurableObject (id TEXT PRIMARY KEY);
